version: '3.8'

services:
  polandrent-app:
    build: .
    container_name: polandrent_container
    env_file:
      - .env
    volumes:
      - ./polandrent.db:/app/polandrent.db
    command: >
      bash -c "alembic upgrade head && 
               python app/services/scraper.py && 
               python app/services/analytics.py"