"""Initial_migration

Revision ID: 54e2077e9d54
Revises: 
Create Date: 2026-07-16 18:13:11.660597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e2077e9d54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'pets_allowed')
    op.drop_column('apartments', 'is_furnished')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('is_furnished', sa.BOOLEAN(), nullable=True))
    op.add_column('apartments', sa.Column('pets_allowed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
